import { spawn } from "child_process";
import fs from "fs/promises";
import path from "path";
import { type Clip, type Job, updateJob } from "./job-store";
import { clipVideo, ffprobe, formatDuration } from "./ffmpeg";
import { detectByInterval, detectHighlights } from "./highlight-detector";
import { mergeShortSegments, parseVTT, parseSRT } from "./subtitle-parser";

const TMP_DIR = "/tmp/peakclipper";

// Flags applied to every yt-dlp invocation.
// - android client: bypasses bot detection for most videos
// - js-runtimes node: use installed Node.js for JS-based extraction
// - cookies: optional file path via YTDLP_COOKIES_FILE env var (Netscape format)
function ytdlpBase(): string[] {
  const base = [
    "--no-check-certificate",
    "--extractor-args", "youtube:player_client=android,web",
    "--js-runtimes", "node",
    "--no-playlist",
  ];
  const cookiesFile = process.env.YTDLP_COOKIES_FILE;
  if (cookiesFile) base.push("--cookies", cookiesFile);
  return base;
}

// Piped instances used as fallback when YouTube blocks direct yt-dlp on datacenter IPs.
const PIPED_INSTANCES = [
  "https://pipedapi.kavin.rocks",
  "https://api.piped.projectsegfault.net",
  "https://piped-api.garudalinux.org",
];

interface PipedData {
  title: string;
  duration: number;
  thumbnailUrl: string;
  uploader: string;
  videoStreams: Array<{ url: string; mimeType: string; quality: string; videoOnly: boolean; bitrate: number }>;
  audioStreams: Array<{ url: string; mimeType: string; bitrate: number }>;
  subtitles: Array<{ url: string; mimeType: string; code: string; autoGenerated: boolean }>;
}

function extractYouTubeId(url: string): string | null {
  const m = url.match(/(?:v=|\/v\/|youtu\.be\/|\/embed\/|\/shorts\/)([a-zA-Z0-9_-]{11})/);
  return m?.[1] ?? null;
}

function isBotError(msg: string): boolean {
  return msg.includes("Sign in") || msg.includes("bot") || msg.includes("cookies") || msg.includes("Login");
}

async function fetchPiped(videoId: string): Promise<PipedData | null> {
  for (const instance of PIPED_INSTANCES) {
    try {
      const resp = await fetch(`${instance}/streams/${videoId}`, {
        headers: { "User-Agent": "PeakClipper/1.0" },
        signal: AbortSignal.timeout(10_000),
      });
      if (!resp.ok) continue;
      return await resp.json() as PipedData;
    } catch { /* try next */ }
  }
  return null;
}

// YouTube oEmbed — always works for public videos, no auth needed
async function fetchOembed(videoId: string): Promise<{ title: string; channel: string; thumbnail: string } | null> {
  try {
    const url = `https://www.youtube.com/oembed?url=https://www.youtube.com/watch?v=${videoId}&format=json`;
    const resp = await fetch(url, { signal: AbortSignal.timeout(8_000) });
    if (!resp.ok) return null;
    const d = await resp.json() as { title: string; author_name: string; thumbnail_url: string };
    return { title: d.title, channel: d.author_name, thumbnail: d.thumbnail_url };
  } catch { return null; }
}

// cobalt.tools — free YouTube downloader API, handles auth on their side
async function fetchCobaltUrl(url: string): Promise<string | null> {
  try {
    const resp = await fetch("https://api.cobalt.tools/", {
      method: "POST",
      headers: { "Content-Type": "application/json", "Accept": "application/json" },
      body: JSON.stringify({ url, videoQuality: "720", filenameStyle: "basic" }),
      signal: AbortSignal.timeout(20_000),
    });
    if (!resp.ok) return null;
    const d = await resp.json() as { status: string; url?: string };
    return d.url ?? null;
  } catch { return null; }
}

const sleep = (ms: number) => new Promise<void>((r) => setTimeout(r, ms));

function checkBinaries(): Promise<boolean> {
  return new Promise((resolve) => {
    const proc = spawn("yt-dlp", ["--version"]);
    proc.on("error", () => resolve(false)); // any spawn error → demo mode
    proc.on("close", (code) => resolve(code === 0));
  });
}

const DEMO_CLIPS_DATA = [
  {
    title: "The mindset shift that separates 7-figure creators from everyone else",
    transcript: "Most people think growing an audience is about posting more content. The real secret? Consistency isn't about volume — it's about creating a content system that compounds over time. Here's exactly what changed when I shifted my strategy.",
  },
  {
    title: "Why 90% of people quit before they see results (and how to be the 10%)",
    transcript: "The number one reason people don't succeed online isn't lack of talent or resources. It's the gap between expectation and reality in the first 90 days. I call it the 'trough of disillusionment' and once you understand it, you can push through it.",
  },
  {
    title: "This simple framework 10x'd my content output without burning out",
    transcript: "I used to spend 8 hours on a single video. Now I batch three in the same time. The secret is the Content Pillar Framework — you pick 5 core topics and you never run out of ideas again. Let me walk you through exactly how it works.",
  },
  {
    title: "The uncomfortable truth about algorithm-chasing (and what works instead)",
    transcript: "Every time the algorithm changes, half the creators I know panic and pivot. But the channels that consistently grow? They ignored the algorithm and focused on one thing: being genuinely useful to a specific person. Here's the strategy.",
  },
  {
    title: "How to turn one long-form video into 30 pieces of content",
    transcript: "This is the content repurposing system that every top creator uses but nobody talks about. You start with one anchor piece — a podcast, interview, or long video — and extract clips, quotes, carousels, threads, and blog posts from it. One hour of recording, 30 days of content.",
  },
];

const DEMO_TITLES_POOL = [
  "How I Grew from 0 to 100K Subscribers in 12 Months",
  "The Content Strategy That Actually Works in 2024",
  "Why Most Creators Quit (And How to Be the 10% Who Don't)",
  "Behind the Scenes: My Full Content Creation Process",
  "5 Lessons from Building a 7-Figure Creator Business",
];

function demoTitleFromUrl(url: string): string {
  try {
    const parsed = new URL(url);
    const pathParts = parsed.pathname.split("/").filter(Boolean);
    const lastPart = pathParts[pathParts.length - 1]
      ?.replace(/[-_]/g, " ")
      ?.replace(/\.[^.]+$/, "")
      ?.replace(/\b\w/g, (c) => c.toUpperCase());
    if (lastPart && lastPart.length > 8 && lastPart.length < 80) return lastPart;
    const host = parsed.hostname.replace("www.", "");
    if (host && !host.includes("youtube") && !host.includes("youtu.be")) {
      return `Video from ${host.charAt(0).toUpperCase() + host.slice(1)}`;
    }
  } catch { /* not a URL */ }
  const base = url.split("/").pop()?.replace(/\.[^.]+$/, "")?.replace(/[-_]/g, " ");
  if (base && base.length > 4 && base.length < 80) {
    return base.charAt(0).toUpperCase() + base.slice(1);
  }
  const hash = url.split("").reduce((a, c) => a + c.charCodeAt(0), 0);
  return DEMO_TITLES_POOL[hash % DEMO_TITLES_POOL.length];
}

async function runDemoMode(job: Job): Promise<void> {
  const { id, url } = job;

  updateJob(id, { status: "fetching_info", progress: 8, currentStep: "Fetching video info…" });
  await sleep(1000);

  updateJob(id, {
    videoInfo: { title: demoTitleFromUrl(url), duration: 1847, thumbnail: "", channel: "Demo", url },
    status: "downloading",
    progress: 12,
    currentStep: "Downloading video…",
  });

  for (let p = 12; p <= 55; p += 3) {
    updateJob(id, { progress: p });
    await sleep(110);
  }

  updateJob(id, { status: "extracting_transcript", progress: 57, currentStep: "Extracting transcript…" });
  await sleep(900);

  updateJob(id, { status: "analyzing", progress: 66, currentStep: "Finding best moments…" });
  await sleep(700);

  const count = DEMO_CLIPS_DATA.length;
  updateJob(id, { status: "clipping", progress: 72, currentStep: `Generating ${count} clips…` });

  const clips: Clip[] = [];
  for (let i = 0; i < count; i++) {
    await sleep(450);
    const c = DEMO_CLIPS_DATA[i];
    const startTime = 60 + i * 320;
    const duration = 45 + (i % 3) * 10;
    clips.push({
      id: `${id}_demo${i}`,
      jobId: id,
      title: c.title,
      startTime,
      endTime: startTime + duration,
      duration,
      score: 95 - i * 8,
      transcript: c.transcript,
    });
    updateJob(id, {
      progress: 72 + (i + 1) * 5,
      clips: [...clips],
      currentStep: `Clipped ${i + 1}/${count}…`,
    });
  }

  updateJob(id, { status: "done", progress: 100, currentStep: "Done!", clips });
}

async function ensureDirs() {
  await fs.mkdir(`${TMP_DIR}/downloads`, { recursive: true });
  await fs.mkdir(`${TMP_DIR}/clips`, { recursive: true });
  await fs.mkdir(`${TMP_DIR}/uploads`, { recursive: true });
}

function runCommand(
  cmd: string,
  args: string[],
  onStderr?: (line: string) => void
): Promise<string> {
  return new Promise((resolve, reject) => {
    let stdout = "";
    let stderr = "";
    const proc = spawn(cmd, args);
    proc.stdout.on("data", (d: Buffer) => (stdout += d.toString()));
    proc.stderr.on("data", (d: Buffer) => {
      const text = d.toString();
      stderr += text;
      onStderr?.(text);
    });
    proc.on("close", (code) => {
      if (code === 0) resolve(stdout);
      else reject(new Error(stderr.slice(-800)));
    });
    proc.on("error", reject);
  });
}

// Piped-fronted URL for yt-dlp's built-in Piped extractor (no YouTube auth needed)
const PIPED_FRONTEND_HOSTS = [
  "piped.video",
  "piped.adminforge.de",
  "piped.smnz.de",
  "piped.yt",
];

function toPipedUrl(videoId: string, hostIndex = 0): string {
  return `https://${PIPED_FRONTEND_HOSTS[hostIndex % PIPED_FRONTEND_HOSTS.length]}/watch?v=${videoId}`;
}

// yt-dlp flags for non-YouTube URLs (no youtube-specific extractor-args needed)
function ytdlpBaseGeneric(): string[] {
  const base = ["--no-check-certificate", "--no-playlist"];
  const cookiesFile = process.env.YTDLP_COOKIES_FILE;
  if (cookiesFile) base.push("--cookies", cookiesFile);
  return base;
}

async function getVideoInfo(url: string) {
  // Step 1: direct YouTube via yt-dlp
  try {
    const json = await runCommand("yt-dlp", [...ytdlpBase(), "--dump-json", url]);
    const data = JSON.parse(json);
    return {
      title: data.title as string,
      duration: data.duration as number,
      thumbnail: (data.thumbnail || data.thumbnails?.[0]?.url || "") as string,
      channel: (data.channel || data.uploader || "Unknown") as string,
      url,
    };
  } catch (err) {
    if (!isBotError(err instanceof Error ? err.message : "") || !extractYouTubeId(url)) throw err;
  }

  const videoId = extractYouTubeId(url)!;

  // Step 2: yt-dlp via piped.video frontend (bypasses bot detection natively)
  for (let i = 0; i < PIPED_FRONTEND_HOSTS.length; i++) {
    try {
      const json = await runCommand("yt-dlp", [
        ...ytdlpBaseGeneric(), "--dump-json", toPipedUrl(videoId, i),
      ]);
      const data = JSON.parse(json);
      return {
        title: data.title as string,
        duration: data.duration as number,
        thumbnail: (data.thumbnail || data.thumbnails?.[0]?.url || "") as string,
        channel: (data.channel || data.uploader || "Unknown") as string,
        url,
      };
    } catch { /* try next */ }
  }

  // Step 3: Piped API JSON fallback
  const piped = await fetchPiped(videoId);
  if (piped) {
    return {
      title: piped.title,
      duration: piped.duration,
      thumbnail: piped.thumbnailUrl ?? "",
      channel: piped.uploader ?? "Unknown",
      url,
    };
  }

  // Step 4: YouTube oEmbed — always works for public videos, no auth
  const oembed = await fetchOembed(videoId);
  if (oembed) {
    return { title: oembed.title, duration: 0, thumbnail: oembed.thumbnail, channel: oembed.channel, url };
  }

  throw new Error("Unable to fetch video info — YouTube is blocking this server IP. Try uploading the video file directly.");
}

async function downloadViaYtdlp(
  url: string,
  destDir: string,
  jobId: string,
  onProgress: (p: number) => void
): Promise<string> {
  const outputTemplate = path.join(destDir, `${jobId}.%(ext)s`);
  await runCommand(
    "yt-dlp",
    [
      ...ytdlpBase(),
      "-f", "bestvideo[height<=720][ext=mp4]+bestaudio[ext=m4a]/best[height<=720][ext=mp4]/best[height<=720]",
      "--merge-output-format", "mp4",
      "-o", outputTemplate,
      url,
    ],
    (line) => {
      const match = line.match(/(\d+\.\d+)%/);
      if (match) onProgress(parseFloat(match[1]));
    }
  );
  const files = await fs.readdir(destDir);
  const found = files.find((f) => f.startsWith(jobId) && f.endsWith(".mp4"));
  if (!found) throw new Error("Downloaded file not found");
  return path.join(destDir, found);
}

async function downloadViaPiped(
  url: string,
  destDir: string,
  jobId: string,
  onProgress: (p: number) => void
): Promise<string> {
  const videoId = extractYouTubeId(url);
  if (!videoId) throw new Error("Not a YouTube URL — Piped fallback unavailable");

  const data = await fetchPiped(videoId);
  if (!data) throw new Error("All Piped instances unavailable — try uploading the video file directly");

  // Prefer combined mp4 stream (video+audio, no merge needed)
  const combined = data.videoStreams
    .filter(s => !s.videoOnly && s.mimeType?.includes("mp4"))
    .sort((a, b) => parseInt(b.quality) - parseInt(a.quality));

  // Fall back to highest-bitrate video-only + best audio
  const videoOnly = data.videoStreams
    .filter(s => s.videoOnly && s.mimeType?.includes("mp4"))
    .sort((a, b) => parseInt(b.quality) - parseInt(a.quality));

  const bestAudio = data.audioStreams
    .filter(s => s.mimeType?.includes("mp4") || s.mimeType?.includes("m4a"))
    .sort((a, b) => b.bitrate - a.bitrate)[0];

  const outputPath = path.join(destDir, `${jobId}.mp4`);

  if (combined[0]) {
    // Single stream download via yt-dlp generic extractor
    await runCommand(
      "yt-dlp",
      ["--no-check-certificate", "-o", outputPath, combined[0].url],
      (line) => { const m = line.match(/(\d+\.\d+)%/); if (m) onProgress(parseFloat(m[1])); }
    );
  } else if (videoOnly[0] && bestAudio) {
    // Download both and merge with ffmpeg
    const videoPath = path.join(destDir, `${jobId}_v.mp4`);
    const audioPath = path.join(destDir, `${jobId}_a.mp4`);
    await runCommand("yt-dlp", ["--no-check-certificate", "-o", videoPath, videoOnly[0].url],
      (line) => { const m = line.match(/(\d+\.\d+)%/); if (m) onProgress(parseFloat(m[1]) * 0.5); });
    await runCommand("yt-dlp", ["--no-check-certificate", "-o", audioPath, bestAudio.url],
      (line) => { const m = line.match(/(\d+\.\d+)%/); if (m) onProgress(50 + parseFloat(m[1]) * 0.5); });
    await runCommand("ffmpeg", ["-y", "-i", videoPath, "-i", audioPath, "-c", "copy", outputPath]);
    await fs.rm(videoPath, { force: true }).catch(() => {});
    await fs.rm(audioPath, { force: true }).catch(() => {});
  } else {
    throw new Error("No playable streams found via Piped");
  }

  return outputPath;
}

async function downloadVideo(
  url: string,
  destDir: string,
  jobId: string,
  onProgress: (p: number) => void
): Promise<string> {
  // Step 1: direct YouTube
  try {
    return await downloadViaYtdlp(url, destDir, jobId, onProgress);
  } catch (err) {
    if (!isBotError(err instanceof Error ? err.message : "") || !extractYouTubeId(url)) throw err;
  }

  const videoId = extractYouTubeId(url)!;

  // Step 2: yt-dlp via piped.video frontend (built-in extractor, no YouTube auth)
  for (let i = 0; i < PIPED_FRONTEND_HOSTS.length; i++) {
    try {
      const outputTemplate = path.join(destDir, `${jobId}.%(ext)s`);
      await runCommand(
        "yt-dlp",
        [
          ...ytdlpBaseGeneric(),
          "-f", "bestvideo[height<=720][ext=mp4]+bestaudio[ext=m4a]/best[height<=720]",
          "--merge-output-format", "mp4",
          "-o", outputTemplate,
          toPipedUrl(videoId, i),
        ],
        (line) => { const m = line.match(/(\d+\.\d+)%/); if (m) onProgress(parseFloat(m[1])); }
      );
      const files = await fs.readdir(destDir);
      const found = files.find((f) => f.startsWith(jobId) && f.endsWith(".mp4"));
      if (found) return path.join(destDir, found);
    } catch { /* try next host */ }
  }

  // Step 3: manual Piped API stream download
  try {
    return await downloadViaPiped(url, destDir, jobId, onProgress);
  } catch { /* fall through */ }

  // Step 4: cobalt.tools — free YouTube downloader, handles auth on their side
  const cobaltUrl = await fetchCobaltUrl(url);
  if (cobaltUrl) {
    const outputPath = path.join(destDir, `${jobId}.mp4`);
    await runCommand(
      "yt-dlp",
      ["--no-check-certificate", "-o", outputPath, cobaltUrl],
      (line) => { const m = line.match(/(\d+\.\d+)%/); if (m) onProgress(parseFloat(m[1])); }
    );
    if (await fs.stat(outputPath).then(() => true).catch(() => false)) return outputPath;
  }

  throw new Error("All download methods failed. YouTube is heavily blocking this server IP. Please upload the video file directly.");
}

async function extractSubtitlesViaPiped(
  videoId: string,
  destDir: string,
  language: string
): Promise<string | null> {
  const data = await fetchPiped(videoId);
  if (!data?.subtitles?.length) return null;

  const langs = [language, "en", "id"];
  const sub = data.subtitles.find(
    s => s.autoGenerated && langs.some(l => s.code?.startsWith(l))
  ) ?? data.subtitles.find(s => langs.some(l => s.code?.startsWith(l)));

  if (!sub) return null;

  const resp = await fetch(sub.url, { signal: AbortSignal.timeout(15_000) });
  if (!resp.ok) return null;

  const ext = sub.mimeType?.includes("vtt") ? "vtt" : "srt";
  const outPath = path.join(destDir, `subs.${ext}`);
  await fs.writeFile(outPath, await resp.text(), "utf-8");
  return outPath;
}

async function extractSubtitles(
  url: string,
  destDir: string,
  language: string
): Promise<string | null> {
  const langs = [language, "en", "id"].filter(Boolean).join(",");
  const outputTemplate = path.join(destDir, "subs");

  try {
    await runCommand("yt-dlp", [
      ...ytdlpBase(),
      "--write-auto-sub",
      "--sub-lang", langs,
      "--sub-format", "vtt",
      "--skip-download",
      "-o", outputTemplate,
      url,
    ]);
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    const videoId = extractYouTubeId(url);
    if (!isBotError(msg) || !videoId) return null;

    // Retry via piped.video frontend
    for (let i = 0; i < PIPED_FRONTEND_HOSTS.length; i++) {
      try {
        await runCommand("yt-dlp", [
          ...ytdlpBaseGeneric(),
          "--write-auto-sub",
          "--sub-lang", langs,
          "--sub-format", "vtt",
          "--skip-download",
          "-o", outputTemplate,
          toPipedUrl(videoId, i),
        ]);
        break;
      } catch { /* try next */ }
    }

    // Piped API subtitle fallback
    return extractSubtitlesViaPiped(videoId, destDir, language);
  }

  const files = await fs.readdir(destDir);
  const sub = files.find((f) => f.startsWith("subs") && (f.endsWith(".vtt") || f.endsWith(".srt")));
  if (!sub) return null;
  return path.join(destDir, sub);
}

async function readSubtitleFile(filePath: string): Promise<string> {
  return fs.readFile(filePath, "utf-8");
}

export async function processVideo(job: Job): Promise<void> {
  if (!(await checkBinaries())) {
    return runDemoMode(job);
  }

  const { id, url, settings, localFilePath } = job;

  await ensureDirs();
  const jobDir = path.join(TMP_DIR, "downloads", id);
  await fs.mkdir(jobDir, { recursive: true });

  try {
    let videoPath: string;
    let videoDuration = 0;

    if (localFilePath) {
      // --- File upload path ---
      videoPath = localFilePath;
      updateJob(id, {
        status: "fetching_info",
        progress: 10,
        currentStep: "Analyzing uploaded video…",
      });

      const probe = await ffprobe(videoPath);
      videoDuration = probe.duration;

      updateJob(id, {
        videoInfo: {
          title: path.basename(url || localFilePath, path.extname(url || localFilePath)),
          duration: probe.duration,
          thumbnail: "",
          channel: "Uploaded file",
          url: localFilePath,
        },
        progress: 20,
      });
    } else {
      // --- URL download path ---
      updateJob(id, {
        status: "fetching_info",
        progress: 5,
        currentStep: "Fetching video info…",
      });

      const info = await getVideoInfo(url);
      videoDuration = info.duration;

      updateJob(id, {
        videoInfo: info,
        status: "downloading",
        progress: 10,
        currentStep: "Downloading video…",
      });

      videoPath = await downloadVideo(url, jobDir, id, (pct) => {
        updateJob(id, { progress: 10 + pct * 0.45 });
      });
    }

    // --- Extract / generate transcript ---
    updateJob(id, {
      status: "extracting_transcript",
      progress: 57,
      currentStep: "Extracting transcript…",
    });

    let segments = null;

    if (!localFilePath) {
      // Try YouTube auto-captions
      const subFile = await extractSubtitles(url, jobDir, settings.language);
      if (subFile) {
        const content = await readSubtitleFile(subFile);
        const raw = subFile.endsWith(".srt") ? parseSRT(content) : parseVTT(content);
        segments = mergeShortSegments(raw);
      }
    }

    // --- Highlight detection ---
    updateJob(id, {
      status: "analyzing",
      progress: 65,
      currentStep: "Finding best moments…",
    });

    const candidates =
      segments && segments.length >= 5
        ? detectHighlights(segments, settings.clipLength)
        : detectByInterval(videoDuration, settings.clipLength);

    // --- Clip the video ---
    updateJob(id, {
      status: "clipping",
      progress: 70,
      currentStep: `Generating ${candidates.length} clips…`,
    });

    const clips: Clip[] = [];
    const clipsDir = path.join(TMP_DIR, "clips");

    const perClipShare = 28 / Math.max(candidates.length, 1);
    for (let i = 0; i < candidates.length; i++) {
      const c = candidates[i];
      const clipId = `${id}_clip${i}`;
      const outputPath = path.join(clipsDir, `${clipId}.mp4`);
      const base = 70 + i * perClipShare;

      await clipVideo(
        videoPath,
        outputPath,
        c.startTime,
        c.endTime,
        settings.aspectRatio,
        settings.captions,
        c.transcript.slice(0, 120),
        (pct) => {
          updateJob(id, { progress: base + (pct / 100) * perClipShare });
        }
      );

      clips.push({
        id: clipId,
        jobId: id,
        title: c.title,
        startTime: c.startTime,
        endTime: c.endTime,
        duration: c.endTime - c.startTime,
        score: c.score,
        filePath: outputPath,
        transcript: c.transcript,
      });

      updateJob(id, {
        progress: 70 + ((i + 1) / candidates.length) * 28,
        currentStep: `Clipped ${i + 1}/${candidates.length}…`,
      });
    }

    updateJob(id, {
      status: "done",
      progress: 100,
      currentStep: "Done!",
      clips,
    });
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    updateJob(id, {
      status: "error",
      error: message,
      currentStep: "Failed",
    });
  } finally {
    // Cleanup download directory (keep clips)
    fs.rm(jobDir, { recursive: true, force: true }).catch(() => {});
    // Cleanup uploaded file
    if (localFilePath?.startsWith("/tmp/peakclipper/uploads/")) {
      fs.rm(localFilePath, { force: true }).catch(() => {});
    }
  }
}
